export const GameConfig = {
  world: {
    width: 6400,
    groundYOffset: 48,
  },
  player: {
    moveSpeed: 180,
    jumpVelocity: -380,
    scale: 2,
    maxHealth: 100,
    invincibilityDuration: 1000,
    damageReceived: 10,
    knockbackX: 200,
    knockbackY: -120,
    damageTintDuration: 200,
    restartDelay: 2000,
    bodyWidth: 20,
    bodyHeight: 40,
    bodyOffsetX: 18,
    bodyOffsetY: 14,
    spawnX: 100,
    spawnYOffset: -60,
    idleVelocityThreshold: 10,
  },
  enemy: {
    count: 6,
    scale: 1.8,
    health: 50,
    speed: 60,
    chaseSpeed: 100,
    chaseRange: 200,
    attackRange: 45,
    damageDealt: 25,
    knockbackX: 150,
    knockbackY: -100,
    deathDelay: 1500,
    attackCooldown: 1200,
    tintDuration: 150,
    deathScore: 100,
    bodyWidth: 20,
    bodyHeight: 40,
    bodyOffsetX: 18,
    bodyOffsetY: 14,
    spawnYOffset: -60,
  },
  boss: {
    scale: 3,
    health: 500,
    speed: 80,
    chaseSpeed: 140,
    chaseRange: 300,
    attackRange: 80,
    damageDealt: 20,
    knockbackX: 250,
    knockbackY: -180,
    deathDelay: 2000,
    attackCooldown: 800,
    tintDuration: 200,
    deathScore: 1000,
    bodyWidth: 36,
    bodyHeight: 52,
    bodyOffsetX: 10,
    bodyOffsetY: 4,
    spawnYOffset: -80,
    phases: [
      { healthPercent: 1.0, attackPattern: 'slash' as const },
      { healthPercent: 0.6, attackPattern: 'slash_rapid' as const },
      { healthPercent: 0.3, attackPattern: 'enrage' as const },
    ],
    projectile: {
      speed: 200,
      damage: 15,
      fireRate: 2000,
      count: 1,
      spread: 0,
    },
    healthBarWidth: 300,
    healthBarHeight: 20,
    healthBarY: 30,
    healthBarBorderColor: 0xffffff,
    healthBarBorderAlpha: 0.8,
    healthBarBgColor: 0x333333,
    healthBarBgAlpha: 0.8,
    healthBarHighColor: 0xcc44cc,
    healthBarMidColor: 0xcc6644,
    healthBarLowColor: 0xcc2222,
    healthBarHighThreshold: 0.6,
    healthBarLowThreshold: 0.3,
    nameColor: '#ff88cc',
    nameFontSize: '20px',
    nameFontFamily: 'Georgia, serif',
    warningColor: '#ff4444',
    warningFontSize: '36px',
    warningFontFamily: 'Georgia, serif',
    warningDuration: 2000,
  },
  token: {
    types: {
      crystal: {
        scoreValue: 50,
        healthValue: 0,
        scale: 1.5,
        tint: 0x44ddff,
        glowColor: 0x88eeff,
        glowAlpha: 0.4,
        bounceHeight: 6,
        bounceDuration: 600,
        floatAmplitude: 3,
        floatDuration: 1200,
      },
      coin: {
        scoreValue: 10,
        healthValue: 0,
        scale: 1.2,
        tint: 0xffdd44,
        glowColor: 0xffee88,
        glowAlpha: 0.3,
        bounceHeight: 5,
        bounceDuration: 500,
        floatAmplitude: 2,
        floatDuration: 1000,
      },
      heart: {
        scoreValue: 0,
        healthValue: 25,
        scale: 1.4,
        tint: 0xff4466,
        glowColor: 0xff8899,
        glowAlpha: 0.5,
        bounceHeight: 7,
        bounceDuration: 700,
        floatAmplitude: 4,
        floatDuration: 1400,
      },
    },
    collectRadius: 30,
    magnetRadius: 80,
    magnetSpeed: 300,
    collectEffectDuration: 400,
    collectTextFontSize: '18px',
    collectTextDuration: 800,
    collectTextRiseSpeed: 40,
    particleCount: 8,
    particleSpeed: 80,
    particleLifespan: 400,
  },
  level: {
    current: 0 as number,
    levels: [
      {
        name: 'Verdant Plains',
        worldWidth: 6400,
        bossX: 6000,
        backgroundTheme: 'forest' as const,
        enemyCount: 6,
        tokenCount: 15,
        platformCount: 6,
      },
      {
        name: 'Shadow Caverns',
        worldWidth: 8000,
        bossX: 7600,
        backgroundTheme: 'cavern' as const,
        enemyCount: 10,
        tokenCount: 25,
        platformCount: 10,
      },
      {
        name: 'Crimson Peak',
        worldWidth: 10000,
        bossX: 9600,
        backgroundTheme: 'mountain' as const,
        enemyCount: 14,
        tokenCount: 35,
        platformCount: 14,
      },
    ],
  },
  combat: {
    playerAttackRange: 60,
    playerSpellRange: 80,
  },
  camera: {
    followLerpX: 0.08,
    followLerpY: 0.08,
    deadzoneWidth: 100,
    deadzoneHeight: 50,
  },
  hud: {
    healthBarX: 40,
    healthBarY: 16,
    healthBarWidth: 120,
    healthBarHeight: 16,
    healthHighThreshold: 0.5,
    healthLowThreshold: 0.25,
    healthBarBgColor: 0x333333,
    healthBarBgAlpha: 0.8,
    healthBarHighColor: 0x44cc44,
    healthBarMidColor: 0xccaa44,
    healthBarLowColor: 0xcc4444,
    healthBarBorderColor: 0xffffff,
    healthBarBorderAlpha: 0.6,
    healthBarBorderWidth: 1,
    scoreColor: '#ffffff',
    scoreFontSize: '14px',
    tokenCounterColor: '#ffdd44',
    tokenCounterFontSize: '16px',
    tokenCounterX: 200,
    tokenCounterY: 16,
    levelNameColor: '#aaccff',
    levelNameFontSize: '16px',
    levelNameDuration: 3000,
  },
  ui: {
    localStorageKey: 'wizai_settings',
  },
  debug: {
    logLevel: (import.meta.env.PROD ? 'warn' : 'debug') as 'debug' | 'info' | 'warn' | 'error',
    enabled: import.meta.env.DEV ? true : false,
  },
  parallax: {
    layers: [
      { key: 'sky', scrollFactor: 0.02, alpha: 1.0, tint: 0x000000 },
      { key: 'mountains-far', scrollFactor: 0.08, alpha: 1.0, tint: 0x000000 },
      { key: 'mountains-near', scrollFactor: 0.18, alpha: 1.0, tint: 0x000000 },
      { key: 'trees-far', scrollFactor: 0.35, alpha: 1.0, tint: 0x000000 },
      { key: 'trees-near', scrollFactor: 0.6, alpha: 1.0, tint: 0x000000 },
      { key: 'ground-fg', scrollFactor: 0.85, alpha: 0.4, tint: 0x000000 },
    ],
    fog: {
      enabled: true,
      color: 0x88aacc,
      alpha: 0.15,
      speed: 0.02,
    },
    particles: {
      count: 40,
      speedMin: 0.15,
      speedMax: 0.5,
      sizeMin: 1,
      sizeMax: 3,
      alphaMin: 0.1,
      alphaMax: 0.35,
      color: 0xccddff,
      sineFactor: 0.015,
      sineAmplitude: 0.25,
      yLimitOffset: -80,
      respawnYOffset: -10,
      spawnYOffset: 10,
    },
    themes: {
      forest: {
        skyColors: [0x1a1a3a, 0x2a4a6a, 0x5a8aaa],
        mountainFarColor: 0x2a4a3a,
        mountainNearColor: 0x3a6a4a,
        treeFarColor: 0x2a5a2a,
        treeNearColor: 0x3a7a3a,
        groundColor: 0x3a5a40,
        groundTopColor: 0x588157,
        fogColor: 0x88aacc,
      },
      cavern: {
        skyColors: [0x0a0a1a, 0x1a1a2a, 0x2a2a3a],
        mountainFarColor: 0x1a1a2a,
        mountainNearColor: 0x2a2a3a,
        treeFarColor: 0x1a2a1a,
        treeNearColor: 0x2a3a2a,
        groundColor: 0x2a2a30,
        groundTopColor: 0x4a4a55,
        fogColor: 0x4a4a5a,
      },
      mountain: {
        skyColors: [0x1a0a2a, 0x3a1a4a, 0x6a3a6a],
        mountainFarColor: 0x4a2a4a,
        mountainNearColor: 0x6a3a5a,
        treeFarColor: 0x3a2a3a,
        treeNearColor: 0x5a3a4a,
        groundColor: 0x4a3a40,
        groundTopColor: 0x7a5a60,
        fogColor: 0x8a6a8a,
      },
    } as const,
  },
  transition: {
    fadeDuration: 500,
    bossWarningDuration: 2500,
    gameOver: {
      fadeInDuration: 1000,
      textPulseDuration: 1500,
      textFontSize: '48px',
      textFontFamily: 'Georgia, serif',
      textColor: '#ff4444',
      subtitleFontSize: '18px',
      subtitleColor: '#cccccc',
      restartDelay: 3000,
    },
    victory: {
      fadeInDuration: 800,
      celebrationDuration: 4000,
      textFontSize: '52px',
      textFontFamily: 'Georgia, serif',
      textColor: '#f0c060',
      subtitleFontSize: '20px',
      subtitleColor: '#aaccff',
    },
  },
} as const;

export type LevelTheme = 'forest' | 'cavern' | 'mountain';
export type TokenType = 'crystal' | 'coin' | 'heart';
export type BossAttackPattern = 'slash' | 'slash_rapid' | 'enrage';

export interface LevelData {
  name: string;
  worldWidth: number;
  bossX: number;
  backgroundTheme: LevelTheme;
  enemyCount: number;
  tokenCount: number;
  platformCount: number;
}
