export const GameConfig = {
  world: {
    width: 3200,
    groundYOffset: 48,
  },
  player: {
    moveSpeed: 180,
    jumpVelocity: -380,
    scale: 2,
    maxHealth: 100,
    invincibilityDuration: 1000,
    damageReceived: 10,
    knockbackX: 200,
    knockbackY: -120,
    damageTintDuration: 200,
    restartDelay: 2000,
    bodyWidth: 20,
    bodyHeight: 40,
    bodyOffsetX: 18,
    bodyOffsetY: 14,
    spawnX: 100,
    spawnYOffset: -60,
    idleVelocityThreshold: 10,
  },
  enemy: {
    count: 6,
    scale: 1.8,
    health: 50,
    speed: 60,
    chaseSpeed: 100,
    chaseRange: 200,
    attackRange: 45,
    damageDealt: 25,
    knockbackX: 150,
    knockbackY: -100,
    deathDelay: 1500,
    attackCooldown: 1200,
    tintDuration: 150,
    deathScore: 100,
    bodyWidth: 20,
    bodyHeight: 40,
    bodyOffsetX: 18,
    bodyOffsetY: 14,
    spawnYOffset: -60,
  },
  combat: {
    playerAttackRange: 60,
    playerSpellRange: 80,
  },
  boss: {
    scale: 3.0,
    health: 200,
    speed: 40,
    chaseSpeed: 80,
    chaseRange: 300,
    attackRange: 70,
    damageDealt: 20,
    knockbackX: 250,
    knockbackY: -150,
    deathDelay: 2500,
    attackCooldown: 1500,
    chargeCooldown: 4000,
    chargeSpeed: 220,
    chargeDuration: 800,
    tintDuration: 200,
    deathScore: 500,
    bodyWidth: 28,
    bodyHeight: 50,
    bodyOffsetX: 14,
    bodyOffsetY: 6,
    spawnYOffset: -80,
    triggerKills: 4,
    spawnX: 2800,
  },
  camera: {
    followLerpX: 0.08,
    followLerpY: 0.08,
    deadzoneWidth: 100,
    deadzoneHeight: 50,
  },
  hud: {
    healthBarX: 40,
    healthBarY: 16,
    healthBarWidth: 120,
    healthBarHeight: 16,
    healthHighThreshold: 0.5,
    healthLowThreshold: 0.25,
    healthBarBgColor: 0x333333,
    healthBarBgAlpha: 0.8,
    healthBarHighColor: 0x44cc44,
    healthBarMidColor: 0xccaa44,
    healthBarLowColor: 0xcc4444,
    healthBarBorderColor: 0xffffff,
    healthBarBorderAlpha: 0.6,
    healthBarBorderWidth: 1,
  },
  ui: {
    localStorageKey: 'wizai_settings',
  },
  debug: {
    logLevel: (import.meta.env.PROD ? 'warn' : 'debug') as 'debug' | 'info' | 'warn' | 'error',
    enabled: import.meta.env.DEV ? true : false,
  },
} as const;
